[install]
# Use the exact versions specified in package.json
exact = true

# Enable global cache to speed up installations
cache = true

# Optimize for production installations
production = false

# Use lockfile for deterministic installations
lockfile = true

# Configure registry
registry = "https://registry.npmjs.org"

# Configure Node.js compatibility
node-register = true

[dev]
# Hot reload settings
hot = true 